using InlineXML.Modules.InlineXml;

namespace InlineXML.Modules.Transformation;

/// <summary>
/// Represents the immutable result of a successful file transformation process.
/// </summary>
/// <remarks>
/// This payload encapsulates the final generated C# source code and the 
/// <see cref="SourceMapEntry"/> collection required to perform reverse-lookup 
/// diagnostics from generated byte offsets back to the original source file.
/// </remarks>
public struct FileTransformedPayload
{
	/// <summary>
	/// Gets or sets the absolute URI or file path of the original source document (e.g., an .xcs file).
	/// </summary>
	/// <value>The unique identifier for the source file.</value>
	public string File { get; set; }

	/// <summary>
	/// Gets or sets the full text content of the generated C# file.
	/// </summary>
	/// <remarks>
	/// ELI5: This is the final "translated" version of your file where all 
	/// the XML has been replaced with C# factory method calls.
	/// </remarks>
	public string Content { get; set; }

	/// <summary>
	/// Gets or sets the collection of source mappings that bridge the original 
	/// XML positions to the new C# positions.
	/// </summary>
	/// <remarks>
	/// ELI5: This is the "GPS" for the compiler. If an error happens in the 
	/// generated code, this list tells us exactly where that code lived in 
	/// your original XML so we can highlight the right line.
	/// </remarks>
	public List<SourceMapEntry> SourceMaps { get; set; }
}